-- CreateTable
CREATE TABLE "Product" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "price" INT4 NOT NULL,
    "description" STRING NOT NULL,
    "image" STRING NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);
